### ISSUE TITLE
Writes

### ISSUE THREAD

**Issue by scottrobertson** [rienafairefr/nYNABapi#1]
Out of interest, have you worked out how to write to the API?

**Comment by rienafairefr** [comment]
Unfortunately the trial ended for me so can't test it anymore. AFAIK, the trick is in the "knowledge" parameters. Basically the server sends you data with a certain knowledge "timestamp", to write you respond with new updated objects, giving the knowledge you had previously and saying you have new knowledge, something like that in theory, first tests were unsuccesfull, but the idea is probably something along those lines.

**Comment by scottrobertson** [comment]
Ahhh interesting. Thank you very much. I shall have a play. I wish they would just release an API!

**Comment by rienafairefr** [comment]
I just pushed a version that permits write. I can successfully write a single transaction. 
They have an API, just a private one :-)

**Comment by scottrobertson** [comment]
Nice! Now i can integrate my getmondo.co.uk card :D

**Comment by rienafairefr** [comment]
Don't freak out the ynab servers with too much requests though ^^

**Comment by scottrobertson** [comment]
1000000 requests sent!

But yeah, that is fine. I may port this to ruby, I hate python (sorry)
