### ISSUE TITLE
Mondo to YNAB

### ISSUE THREAD

**Issue by scottrobertson** [rienafairefr/nYNABapi#10]
This is not really me saying you should build this into the library, but it's a cool idea. Mondo (https://getmondo.co.uk/docs/) have an API with webhooks. It would be pretty cool to push them directly into YNAB.

**Comment by scottrobertson** [comment]
I have released an initial version of this: https://github.com/scottrobertson/mondo-to-ynab

**Comment by rienafairefr** [comment]
Good to see the library used !
