### ISSUE TITLE
I don't think `containsduplicate` is working

### ISSUE THREAD

**Issue by scottrobertson** [rienafairefr/nYNABapi#13]
Hey

I have implemented similar code from the csv import in my repo (https://github.com/scottrobertson/mondo-to-ynab) to check for duplicates. It does not seem to be working. It's allowing me to import them as many times as i want.

**Comment by rienafairefr** [comment]
Is the unit test test_duplicate passing in the source you have checked out ? I just verified HEAD in the master branch and it's passing the csv import duplicate tests, i.e. not importing twice.Maybe the version in pip is out of date

**Comment by scottrobertson** [comment]
I am using the repo directly in git. 

Does the usage look correct? https://github.com/scottrobertson/mondo-to-ynab/blob/master/python/main.py#L72-L76

**Comment by rienafairefr** [comment]
Usage looks fine. Considering Mondo gives you a unique id (the tx_ part), you should probably use it to ensure no duplicates, I did something similar in my OFX import script, using the FITID tag. You can probably save the mondo id in the memo of the transaction to importing into nYNAB, and not import transaction with matching data id.

If it's a webhook, mondo should be sending you only a single request per unique transaction anyway , shouldn't it ?

**Comment by rienafairefr** [comment]
Furthermore containsduplicate is being phased out, in favor of letting consumers (import scripts, and your code) of the library decide what is a duplicate and what's not, I think it makes more sense (how to discriminate a duplicate transaction shouldn't be tied to what's a duplicate account or whatever). I'll commit a major update soon once all the tests pass.
