### ISSUE TITLE
Can use only original budget name

### ISSUE THREAD

**Issue by tereshkin** [rienafairefr/nYNABapi#26]
If budget was renamed I still can use only original budget name to access it. Can't use the name budget was renamed to.

**Comment by rienafairefr** [comment]
Hi tereshkin,
I designed the client like this : the budget name is used when first syncing with the API. The client is created with a given budget name, syncs the catalog info, then looks for that budget name in the data, then selects that budget for the subsequent operations, using the UUID of the budget. If the client is not re-created, then it will continue to use that budget, even if the name of the budget changes on the server. 
Does the problem continue when re-creating the client ? Which version are you using ? 
If re-creating the client is not an option, I could look at the catalog data for each sync and test if the budget name changes, maybe.

**Comment by gehan** [comment]
I have the same problem. I used your lib for the first time ever and it didn't work. To debug I printed all the budgets in some budget list object and the only one there was my budget - but had the original name not the current one. 

I guess then YNAB sends over some versioned list of budgets!? i.e. you'd have to find the latest version of it each budget to find the current name.

**Comment by rienafairefr** [comment]
OK thanks all for the feedback. I can roughly see the problem, I'll test and fix this :-)

**Comment by gehan** [comment]
I guess change the name of your budget and you'll see 😁

**Comment by rienafairefr** [comment]
I've just pushed a bugfix, 59b0961f607f1128d51896789f1821e3a6286d0d, it looks like it works to detect budet name even if the budget is renamed, enjoy !

**Comment by gehan** [comment]
legend thanks! 👍
