### ISSUE TITLE
How to add matched transactions?

### ISSUE THREAD

**Issue by tereshkin** [rienafairefr/nYNABapi#29]
If I just use 'matched_transaction_id' to specify matched transaction Id then 2 transactions appear in YNAB. One of them os shown to be chained but I get exception (in the web app) when trying to unmatch.

**Comment by rienafairefr** [comment]
I've never tested matched transactions through the api. 
I'll investigate the problem, thanks for the feedback. Do you see some info about the error that happens in the web app ? A short snippet that causes the problem would be greatly appreciated as weel :-)
Cheers

**Comment by tereshkin** [comment]
I'm trying to match `transaction_1` and `transaction_orig`.
Following code results into creation of 2 transactions which are shown to be matched but both appear in YNAB list.
(ignore `transaction_2` in this example)

```
    transactions = []
    for i,row in df.iterrows():
        account_id = accounts[row["Account"]].id
        transfer_id = accounts[row["Transfer"]].id

        # Payees:  "Transfer : account_name"
        account_payee_id = payees['Transfer : ' + row["Transfer"]].id
        transfer_payee_id = payees['Transfer : ' + row["Account"]].id
        
        imported_date = datetime.now().date()
        
        payee_name = row["Payee"]
        payee_id = None
        if payee_name:
            if payee_name in payees:
                payee_id = payees[payee_name].id
            else:
                payee_id = add_payee(client, payee_name, None).id
        
        # account to transfer_account
        transaction_1 = Transaction(
            entities_account_id=account_id,
            transfer_account_id=transfer_id,
            entities_payee_id=account_payee_id,
            amount=row["Amount"],
            date=row["Date"],
            imported_date=imported_date,
            imported_payee=payee_name,
            source=None,
            cash_amount=row["Amount"]
        )
        
        # transfer_account to account
        transaction_2 = Transaction(
            entities_account_id=transfer_id,
            transfer_account_id=account_id,
            entities_payee_id=transfer_payee_id,
            amount=-row["Amount"],
            date=row["Date"],
            imported_date=imported_date
        )
        
        transaction_orig = Transaction(
            entities_account_id=account_id,
            amount=row["Amount"],
            date=row["Date"],
            entities_payee_id=payee_id,
            imported_date=imported_date,
            memo=row["Memo"],
            source='Imported'
        )
        
        # match
        transaction_1.matched_transaction_id = transaction_orig.id
        transaction_orig.matched_transaction_id = transaction_1.id
        
        # chain transfers
        transaction_1.transfer_transaction_id = transaction_2.id
        transaction_2.transfer_transaction_id = transaction_1.id
        
        transactions.append(transaction_orig)
        transactions.append(transaction_1)
        transactions.append(transaction_2)

    client.add_transactions(transactions)    
```

**Comment by rienafairefr** [comment]
I confirm reproducibility of the bug, that's a good start for getting it solved !

**Comment by tereshkin** [comment]
This is diff file between 2 dictionary representations before I matched in YNAB app and after.

[matched.diff.txt](https://github.com/rienafairefr/nYNABapi/files/722319/matched.diff.txt)

**Comment by rienafairefr** [comment]
digging into the web app code (appmain.js)  searching for the exception that is seen in javascript console in the browser ("Transactions are matched incorrectly") I find this

    if (e.getSource() == n.Matched && t.getSource() == n.MatchedImport) return e;
    if (e.getSource() == n.MatchedImport && t.getSource() == n.Matched) return t;
    throw new Error("Transactions are matched incorrectly")`

It seems matching is only valid when the source field is correctly entered. One transaction should have `source = 'matched_import'`, the other should have `source = 'Matched'`.
This works without any change to the library code AFAIK:

    transaction_1 = Transaction(
        entities_account_id=account_id,
        entities_payee_id=account_payee_id,
        amount=amount,
        date=date,
        imported_date=imported_date,
        imported_payee=payee_name,
        source='Matched',
        cash_amount=amount
    )
    
    transaction_orig = Transaction(
        entities_account_id=account_id,
        amount=amount,
        date=date,
        entities_payee_id=payee_id,
        imported_date=imported_date,
        memo="",
        source='matched_import'
    )
    
    # match
    transaction_1.matched_transaction_id = transaction_orig.id
    transaction_orig.matched_transaction_id = transaction_1.id
    
    transactions.append(transaction_orig)
    transactions.append(transaction_1)
    
    client.add_transactions(transactions)

I might add a check in the add_transaction code to error out if the transactions dont have th e good source value, not sure how to handle this kind of issues actually (the server does not send an error response when syncing badly matched transactions)

**Comment by tereshkin** [comment]
Ha..

I actually did it. But I didn't spot this works because for some reason YNAB web app didn't show these transactions match. However I can click on the "matched" transactions and unmatch them.  It starts to show everything correct if I do at least 1 manual match/unmatch in the app.

**Comment by rienafairefr** [comment]
Does your final script with chaining with a transfer work with a good value for the source field in the end ?

**Comment by tereshkin** [comment]
Yes. Thanks a lot!

But I have issue I described above: **visual representation** in the app.
Basically it just doesn't show "chain" icons near matched transactions ifI didn't do any manual match/unmatch before.

**Comment by rienafairefr** [comment]
If that's just visual issue, might be a webapp bug, no idea :-) 
I'm closing this, thanks for the feedback
