### ISSUE TITLE
Instructions on how to run manual import

### ISSUE THREAD

**Issue by scottrobertson** [rienafairefr/nYNABapi#3]
Hey

I am not too familiar with Python and how dependancies work, but when I am trying to run `python manualimport.py` i get the following error:

```
Traceback (most recent call last):
  File "manualimport.py", line 4, in <module>
    from ofxtools import OFXTree
ImportError: No module named ofxtools
```

**Comment by rienafairefr** [comment]
I've made it more simple (I think), to handle all the dependencies and run the script, just call `python setup.py install`, then you can call the provided scripts as you did. You're basically missing some dependencies.

**Comment by scottrobertson** [comment]
May be an idea to add that to the readme

**Comment by scottrobertson** [comment]
```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    with open(readme_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by rienafairefr** [comment]
my bad, changed markup to rst, should be solved now
