### ISSUE TITLE
Link PyPI page in the README

### ISSUE THREAD

**Issue by hfaran** [rienafairefr/nYNABapi#31]
I had to search for this to find it: https://pypi.python.org/pypi/pynYNAB

Would be nice if you included:

> # Installation
> 
> ```bash
> pip install pynYNAB
> ```

in the README.

**Comment by rienafairefr** [comment]
I just added it. Yeah, it's kind of inconvenient because the pypi repo and the github repo have different names. The right one would be pynynab but I can't change the github name anymore AFAIK

**Comment by scottrobertson** [comment]
@rienafairefr you can change the github name. It will automatically redirect to the new repo :)

**Comment by hfaran** [comment]
It personally doesn't really bother me if the GitHub repo and the package name are different; so long as I can navigate from one to the other, it's all good :)

**Comment by rienafairefr** [comment]
Thanks Scott, name's been changed :-)
